[versions]
appcompat = "1.7.0"
constraintlayout = "2.2.1"
coreKtx = "1.16.0"
fragmentKtx = "1.8.6"
hilt = "2.43.2"
lifecycle = "2.8.7"
material = "1.12.0"
nav = "2.8.9"
navigationSafeArgsGradlePlugin = "2.5.3"
room = "2.6.1"
roomCompiler = "2.5.2"
kotlin = "1.8.0"
android = "8.9.2"
ksp = "1.8.0-1.0.8"
androidxComposeBom = "2025.04.01"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "nav" }
androidx-navigation-safe-args-gradle-plugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigationSafeArgsGradlePlugin" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "nav" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomCompiler" }

# Compose
androidx-ui-android = { module = "androidx.compose.ui:ui-android" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-foundation-android = { module = "androidx.compose.foundation:foundation-android" }
androidx-material3-android = { module = "androidx.compose.material3:material3-android" }

[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "android" }
android-library = { id = "com.android.library", version.ref = "android"}
devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-kapt = { id = "kotlin-kapt" }
hilt-android-plugin = { id = "dagger.hilt.android.plugin" }
androidx-navigation-safeargs = { id = "androidx.navigation.safeargs.kotlin" }
#compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }