plugins {
    alias libs.plugins.kotlin.android
    alias libs.plugins.android.application
    alias libs.plugins.devtools.ksp
    alias libs.plugins.kotlin.kapt
    alias libs.plugins.hilt.android.plugin
    alias libs.plugins.androidx.navigation.safeargs
    alias libs.plugins.compose.compiler
}

android {
    defaultConfig {
        applicationId "com.brandonjamesyoung.levelup"
        minSdk 33
        targetSdk 35
        compileSdk 35
        versionCode 4
        versionName "0.8.6"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        ksp {
            arg('room.schemaLocation', "$projectDir/schemas")
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.debug
        }
        debug {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }
    buildFeatures {
        viewBinding true
        buildConfig true
        compose true
    }
    composeOptions {
        kotlinCompilerExtensionVersion = '1.4.1'
    }
    namespace 'com.brandonjamesyoung.levelup'
}

dependencies {
    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.androidx.constraintlayout
    implementation libs.material

    // Navigation dependencies
    implementation libs.androidx.fragment.ktx
    implementation libs.androidx.navigation.fragment.ktx
    implementation libs.androidx.navigation.ui.ktx

    // Room dependencies
    implementation libs.androidx.room.runtime
    implementation libs.androidx.room.ktx
    ksp libs.androidx.room.compiler

    // Coroutine dependencies
    implementation libs.androidx.lifecycle.viewmodel.ktx
    implementation libs.androidx.lifecycle.livedata.ktx

    // Hilt dependencies
    implementation libs.hilt.android
    kapt libs.hilt.compiler

    // Compose dependencies
    implementation platform(libs.androidx.compose.bom)
    implementation libs.androidx.ui.android
    implementation libs.androidx.foundation.android
    debugImplementation libs.androidx.compose.ui.tooling
    implementation libs.androidx.material3.android
}

kapt {
    correctErrorTypes true
}